---
- hosts:
        - gitlab_servers
  become: True
  become_method: su
  vars:
          src_dir: 'certs/'
  vars_prompt:
        - name: 'dest_dir'
          prompt: 'Where do you want to copy the /certs to?'
          default: '/etc/gitlab/ssl/'
          private: no
  tasks:
        - name: 'Stop GitLab'
          command: gitlab-ctl stop
        
        - name: 'Add certificates to remote server'
          copy:
                  src:    '{{ item.src }}'
                  dest:   '{{ item.dest }}'
                  owner:  gitlab-www
                  group:  gitlab-www
                  mode:   '{{ item.mode }}'
                  remote_src: no
                  #no_log: true
          with_items:
                  - src:  '{{ src_dir }}'
                    dest: '{{ dest_dir }}'
                    mode: '0644'

        - name: 'Reconfigure Gitlab'
          command: gitlab-ctl reconfigure
        - name: 'Start GitLab'
          command: gitlab-ctl start
