namespace: "hxtree"
name: "lxd_cloud"
version: "0.8.8"
readme: "README.md"
authors:
        - "Matthew Heroux <matthewheroux@gmail.com>"
dependencies:
license:
        - "MIT"
tags:
        - "ansible"
        - "lxd"
        - "backups"
        - "rotates"
        - "kiosks"
        - "nagios"
        - "cloud"
        - "provision"
        - "configure"
        - "hardlink"
        - "server"
        - "management"
repository: "https://github.com/hxtree/LXD-Cloud"
