---
- 
  become: true
  become_method: su
  become_user: root
  connection: ssh
  hosts: 
        - lxd_hosts
  tasks:
    - name: set timezone America/New_York
      timezone:
              name: America/New_York
    - name: "Remove {{ ssh_username }} from all groups"
      user:
       name: "{{ ssh_username }}"
       groups: ''
       append: no

    # Change SSH config to allow it only to login
    - name: 'Replace SSH config to allow user {{ ssh_username }} to SSH and Root to SSH with Key.'
      file:
              state: absent
              path: "/etc/ssh/sshd_config"
    - file:
              state: touch
              path: "/etc/ssh/sshd_config"
    - lineinfile:
              state: present
              insertafter: EOF
              dest: "/etc/ssh/sshd_config"
              line: "{{ item }}"
      with_items:
              - "ChallengeResponseAuthentication no"
              - "UsePAM yes"
              - "X11Forwarding yes"
              - "PrintMotd no"
              - "AcceptEnv LANG LC_*"
              - "Subsystem sftp  /usr/lib/openssh/sftp-server"
              - ""
              - "# allow root and {{ ssh_username }} to ssh"
              - "AllowUsers {{ ssh_username }} root"
              - "PasswordAuthentication yes"
              - "PermitRootLogin yes"
              - ""
              - "# but limit root to SSH key only"
              - "Match User root"
              - "PasswordAuthentication no"
 
    - name: Remove "sudo" package
      apt:
              name: sudo
              state: absent

    - name: "Remove {{ ssh_username }} from all groups"
      user:
               name: "{{ ssh_username }}"
               groups: ''
               append: no

    - name: 'SSHD restart to load new config'
      service:

              name: sshd
              state: restarted
